cmake_minimum_required(VERSION 3.12)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
project(international_file_time LANGUAGES CXX)
add_library(international_file_time SHARED dllmain.cc)
add_subdirectory(nh3api)
target_link_libraries(international_file_time PRIVATE nh3api)
set_target_properties(international_file_time PROPERTIES OUTPUT_NAME "international-file-time")
set_target_properties(international_file_time PROPERTIES PREFIX "")
