cmake_minimum_required(VERSION 3.12)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
project(disable_sbh_heap LANGUAGES CXX)
add_library(disable_sbh_heap SHARED dllmain.cc)
add_subdirectory(nh3api)
target_link_libraries(disable_sbh_heap PRIVATE nh3api)
set_target_properties(disable_sbh_heap PROPERTIES OUTPUT_NAME "disable-sbh-heap")
set_target_properties(disable_sbh_heap PROPERTIES PREFIX "")
